---
title: "10.blups"
author: "Elliott Schmidt"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: true  
    toc_depth: 2
    toc_float: true
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 6
    highlight: monochrome
    theme: cerulean
    latex_engine: xelatex
---

# Blups 

# Load packages 
```{r load-packages-1, warning=FALSE, message=FALSE}
library(tidyverse) # data manipulation
library(ggpubr) # figure arrangement 
library(brms) # Bayesian models
library(StanHeaders)# needed to run Bayesian models
library(rstan) # needed to run Bayesian models
library(standist) # needs to be installed 
library(bayesplot) # needed for MCMC diagnostics 
library(DHARMa) # model validation 
library(ggdist) # partial plots 
library(tidybayes) # partial plots 
library(broom.mixed) # model investigation
library(emmeans) # pairwise comparisons
library(rstanarm) # pairwise comparisons - need for emmeans
library(car) # for vif 
library(lme4) 
library(MuMIn)
```


# Example data 
```{r example-data, eval=FALSE, echo=FALSE}
flowerdata <- read_csv("nph15656-sup-0002-notess3.zip", 
    skip = 10) 

head(flowerdata) 

flowerdata$genotype <- as.factor(flowerdata$genotype)
flowerdata$loc <- as.factor(flowerdata$temperature) 
flowerdata$ctemperature <- scale(flowerdata$temperature) 

model1.1 <- lmer(relativedate ~ ctemperature + (1|loc), REML = FALSE, data = flowerdata) 

temperature_pred <- data.frame(ctemperature = seq(from = min(flowerdata$ctemperature),
                                                 to = max(flowerdata$ctemperature),
                                                 length.out = 50))
temperature_pred$fit1.1 <- predict(model1.1, newdata = temperature_pred, re.form = NA)
```

# Load data
```{r load-data}
ctmax <- read_delim("import_files/CTmax_data.txt", 
    delim = "\t", escape_double = FALSE, 
    col_types = cols(LOE_MEAN_EAS = col_number(), 
        ...30 = col_skip(), ...31 = col_skip()), 
    trim_ws = TRUE)

clutch_data <- read_delim("./import_files/clutch_data_2022_2023.txt")|> 
  mutate(PROJECT_CODE = factor(PROJECT_CODE), 
         FEMALE = factor(FEMALE)) |>
  filter(PROJECT_CODE == "2"| 
         PROJECT_CODE == "3"|
         PROJECT_CODE == "6"|
         PROJECT_CODE == "7")
```

# Data manipulation 

```{r data manipulation, warning=FALSE}
ctmax2 <- ctmax |> 
  mutate(EXP_TANK = factor(EXP_TANK), 
         TRAY_ORD = factor(TRAY_ORD), 
         TRAY_COL = factor(TRAY_COL)) |>
  mutate(EXP_TANK = case_when(EXP_TANK = is.na(EXP_TANK) ~ "999", 
                              TRUE ~ EXP_TANK), 
         TRAY_ORD = case_when(TRAY_ORD = is.na(TRAY_ORD) ~ "999", 
                              TRUE ~ TRAY_ORD), 
         TRAY_COL = case_when(TRAY_COL = is.na(TRAY_COL) ~ "black", 
                              TRUE ~ TRAY_COL)) |>
  mutate(CLUTCH_NUMBER = factor(CLUTCH_NUMBER), 
         MALE = factor(MALE), 
         FEMALE = factor(FEMALE), 
         REGION = factor(REGION), 
         POPULATION = factor(POPULATION), 
         DATE_OF_HATCH = as.Date(DATE_OF_HATCH, format = "%d/%m/%Y"),
         DATE_CTMAX = as.Date(DATE_CTMAX, format = "%d/%m/%Y"),
         DEV_TEMP = factor(DEV_TEMP), 
         LEVEL = as.factor(case_when(TANK >= 1 & TANK <= 199 ~ 1,
                           TANK >= 200 & TANK <= 299 ~ 2,
                           TANK >= 300 & TANK <= 399 ~ 3,
                           TRUE ~ NA_real_)), 
          
         TANK = factor(TANK)) |> 
  left_join(distinct(select(clutch_data, c("CLUTCH_NUMBER", "FEMALE","FEMALE_LAT","CLUTCH_ORDER")), FEMALE, .keep_all = TRUE), by="FEMALE") |> 
  mutate(CLUTCH_ORDER = factor(CLUTCH_ORDER)) |>
  filter(LOE_MEAN_EAS >= 35) |> 
  drop_na(FEMALE) |> 
  drop_na(POPULATION) |> 
  drop_na(TANK) |> 
  drop_na(LEVEL) |> 
  drop_na(CLUTCH_ORDER) |> 
  drop_na(EXPERIMENT) |> 
  drop_na(TRAY_COL) |> 
  drop_na(TRAY_ORD)
```

# Exploratory data analysis 
```{r eda}
ggplot(ctmax2, aes(x=DEV_TEMP, y=LOE_MEAN_EAS, color=FEMALE, fill=FEMALE)) + 
  geom_jitter(width=0.05) + 
  facet_wrap(~FEMALE)
```

# Model1.1
```{r model1.1}
model1.1 <- lmer(LOE_MEAN_EAS ~ 1 + as.numeric(DEV_TEMP) + scale(MASS, center=TRUE, scale=TRUE) + (1 |REGION), 
                 REML=FALSE,
                 data=ctmax2)   

summary(model1.1)
r.squaredGLMM(model1.1)

dev_temp_pred <- data.frame(DEV_TEMP = seq(from=min(as.numeric(ctmax2$DEV_TEMP)), 
                                           to=max(as.numeric(ctmax2$DEV_TEMP)), 
                                           length.out=100), 
                            MASS = 1.320486, length.out=100) 
dev_temp_pred$fit1.1 <- predict(model1.1, newdata = dev_temp_pred, re.form=NA) 

ggplot(dev_temp_pred, aes(x = DEV_TEMP, y = fit1.1)) +
  geom_jitter(data = ctmax2, aes(y = LOE_MEAN_EAS, colour = REGION), width=0.2) +
  geom_line(size = 2) +
  theme_classic() + 
  facet_wrap(~REGION)
``` 

#Model1.2
```{r model1.2}
model1.2 <- lmer(LOE_MEAN_EAS ~ poly(as.numeric(DEV_TEMP), 2, raw = TRUE)+ scale(MASS, scale=TRUE, center=TRUE)  + (1 |REGION), 
                 REML=FALSE,
                 data=ctmax2)  

summary(model1.2)
r.squaredGLMM(model1.2)

dev_temp_pred$fit1.2 <- predict(model1.2, newdata = dev_temp_pred, re.form=NA) 

ggplot(dev_temp_pred, aes(x = DEV_TEMP, y = fit1.2)) +
  geom_jitter(data = ctmax2, aes(y = LOE_MEAN_EAS, colour = REGION), width=0.2) +
  geom_line(size = 2) +
  theme_classic() + 
  facet_wrap(~REGION)
``` 

# Differences between models 
```{r}
chi2 <- 2*(summary(model1.2)$logLik - summary(model1.1)$logLik)
1-pchisq(chi2,1)

# AIC comparison
AIC(model1.1, model1.2, k=2)
```

Yes, the polynomial model is better 

# Model1.3
```{r model1.3}
model1.3 <- lmer(LOE_MEAN_EAS ~ poly(as.numeric(DEV_TEMP), 2, raw = TRUE) + scale(MASS, scale=TRUE, center=TRUE)  + (1 |REGION) + (1 |FEMALE), 
                 REML=FALSE,
                 data=ctmax2) 

summary(model1.3)
r.squaredGLMM(model1.3) 

dev_temp_pred$fit1.3 <- predict(model1.3, newdata = dev_temp_pred, re.form=NA) 
ctmax2$pred_pop1.3 <- predict(model1.3, re.form=NA) 
ctmax2$pred_geno1.3 <- predict(model1.3, re.form =~(1|FEMALE)) 

ggplot(dev_temp_pred, aes(x = DEV_TEMP, y = fit1.3)) +
  geom_jitter(data = ctmax2, aes(y = pred_geno1.3, colour = REGION), width=0.2) +
  geom_smooth(data = ctmax2, 
            aes(y=LOE_MEAN_EAS, group=FEMALE, color=FEMALE), 
            method = "lm")  +
  geom_line(size = 2)+ 
  theme_classic()
```

# Model comparison 
```{r}
chi2 <- 2*(summary(model1.3)$logLik - summary(model1.2)$logLik)
1-pchisq(chi2, 1)

# AIC comparison
AIC(model1.1, model1.2, model1.3, k=2)
```

# Model1.4 
```{r}
model1.4 <- lmer(LOE_MEAN_EAS ~ poly(as.numeric(DEV_TEMP), 2, raw = TRUE)+ scale(MASS, scale=TRUE, center=TRUE)  + (1 |REGION) + (1+DEV_TEMP|FEMALE), 
                 REML=FALSE,
                 data=ctmax2) 

summary(model1.4)
r.squaredGLMM(model1.4) 

dev_temp_pred$fit1.4 <- predict(model1.4, newdata = dev_temp_pred, re.form=NA) 
ctmax2$pred_pop1.4 <- predict(model1.4, re.form=NA) 
ctmax2$pred_geno1.4 <- predict(model1.4, re.form =~(1+DEV_TEMP|FEMALE)) 

ggplot(dev_temp_pred, aes(x = DEV_TEMP, y = fit1.4)) +
  geom_jitter(data = ctmax2, aes(y = pred_geno1.4, colour = REGION), width=0.2) +
  stat_smooth(data = ctmax2, 
            aes(y=LOE_MEAN_EAS, group=FEMALE, color=FEMALE), 
            method="lm", 
            formula=y~poly(x, 3, raw=TRUE), 
            se=FALSE) +
  geom_line(size = 2) + 
  theme_classic()
```

# Model comparison 
```{r}
# Does adding genotype as a random intercept and slope further improve model fit? 
# Likelihood ratio test
chi2 <- 2*(summary(model1.4)$logLik - summary(model1.3)$logLik)
# The df difference between models can be checked by looking at the df within the models being compared
summary(model1.3)$logLik
summary(model1.4)$logLik
# Note that between model1.3 and model1.4 there is a change of 2 df, so the 
# pchisq change needs to be specified with 2 df rather than 1 as in previous comparisons.
1-pchisq(chi2, 2)

# AIC comparison
AIC(model1.1, model1.2, model1.3, model1.4, k=2)
```



# BLUPS 
```{r}
genotype_blups <- ranef(model1.3)$`FEMALE`
genotype_index <- as.data.frame(as.factor(c(1:14)))
genotype_data  <- cbind(genotype_index, genotype_blups)
colnames(genotype_data) <- c("genotype", "BLUP_int") 
```

# BLUPS by intercept
```{r }
genotype_data$genotype_ordered <- factor(genotype_data$genotype, 
                                         levels = genotype_data$genotype[order(genotype_data$BLUP_int)]) 
ggplot(genotype_data, aes(genotype_ordered, BLUP_int)) + 
  geom_point(aes(group = genotype, colour = genotype), size = 4) + 
  ylab("BLUP intercept estimate") +
  geom_hline(yintercept = 0, lty = 2) + theme_classic()  + 
  theme(axis.text.x = element_text(angle =90, vjust=0.5, hjust=1))
```

```{r}
pop =substr(genotype_data$genotype, 1, 1)
genotype_data$pop <- as.factor(pop)

genotype_data$genotype_ordered <- factor(genotype_data$genotype, 
                                         levels = genotype_data$genotype[order(genotype_data$BLUP_int)]) 
genotype_data$genotype <- row.names(genotype_data)
ggplot(genotype_data, aes(genotype_ordered, BLUP_int)) +
  geom_bar(stat = "identity", aes(group = genotype, fill = pop)) +
  xlab("Genotype (in ranked order of plasticity)") +
  ylab("Plasticity (BLUP interecept estimate)") +
  scale_fill_manual(values = c("C" ="firebrick2", 
                               "L" ="dodgerblue3"), 
                    name ="Genotypes", 
                    labels=c("Low-latitude",
                             "High-latitude")) +
  scale_y_continuous(breaks =seq(-0.2,0.2, 0.1), 
                     limits =c(-.2,.2)) +
  theme_classic() + 
  theme(axis.text.x =element_text(angle =45, 
                                  hjust =1))
```
```{r}
pdf("./figures/S_BLUPSoutput_ctmax.pdf", width = 8, height =5)

ggplot(genotype_data, aes(genotype_ordered, BLUP_int)) +
  geom_bar(stat = "identity", aes(group = genotype, fill = pop)) +
  xlab("Genotype (in ranked order of plasticity)") +
  ylab("Plasticity (BLUP interecept estimate)") +
  scale_fill_manual(values = c("C" ="firebrick2", 
                               "L" ="dodgerblue3"), 
                    name ="Genotypes", 
                    labels=c("Low-latitude",
                             "High-latitude"))  +
  scale_y_continuous(breaks =seq(-0.2,0.2, 0.1), 
                     limits =c(-.2,.2)) +
  theme_classic() + 
  theme(axis.text.x =element_text(angle =45, 
                                  hjust =1))

dev.off()
```




Delete everything below

```{r eval =FALSE}
# BLUPs by slope
ggplot(genotype_data, aes(genotype, BLUP_slope)) + 
  geom_point(aes(group = genotype, colour = genotype), size = 4) + 
  ylab("Plasticity (BLUP slope estimate)") +
  geom_hline(yintercept = 0, lty = 2) + theme_classic()
```

```{r eval =FALSE}
# Add the BLUP slopes for the genotypes to the population average
pop_av_slope <- fixef(model1.3)[2]
genotype_data$genotype_slopes <- genotype_blups$DEV_TEMP + pop_av_slope 
genotype_data$genotype <- row.names(genotype_data)
```

```{r eval =FALSE}
# BLUPs by slope + population-level average
ggplot(genotype_data, aes(genotype, genotype_slopes)) + 
  geom_point(aes(group = genotype, colour = genotype), size = 4) + 
  ylab("Plasticity (population-average + BLUP slope estimate)") +
  geom_hline(yintercept = 0, lty = 2) + theme_classic()
```

```{r eval =FALSE}
# Correlation between BLUP intercepts and slopes
ggplot(genotype_data, aes(BLUP_int, BLUP_slope)) +
  geom_point(aes(group = genotype, colour = genotype), size = 4) +
  xlab("BLUP intercept estimate") +
  ylab("BLUP slope estimate") +
  theme_classic()
```

```{r eval =FALSE}
# Rank the BLUPs in order
# Sort BLUPs by slope of most to least plastic
genotype_data$genotype_ordered <- factor(genotype_data$genotype, 
                                         levels = genotype_data$genotype[order(genotype_data$BLUP_slope)])
ggplot(genotype_data, aes(genotype_ordered, BLUP_slope)) +
  geom_bar(stat = "identity", aes(group = genotype, fill = genotype)) +
  xlab("Genotype (in ranked order of plasticity)") +
  ylab("Plasticity (BLUP slope estimate)") +
  theme_classic() + 
  theme(axis.text.x = element_text(angle =90, vjust=0.5, hjust=1))
```

```{r eval =FALSE}
# Another way to visualise the plasticity rank for negative data is by adding
# the BLUP slope values to the population-level average effect of temperature
ggplot(genotype_data, aes(genotype_ordered, genotype_slopes)) +
  geom_bar(stat = "identity", aes(group = genotype, fill = genotype)) +
  xlab("Genotype (in ranked order of plasticity)") +
  ylab("Plasticity (population-average + BLUP slope estimate)") +
  theme_classic()
```

