setwd("./resp_extracted_rates")
file_names <- dir()
lat_resp_dat <- do.call(rbind,lapply(file_names, read.csv))
save(lat_resp_dat, file="../import_files/lat_resp_dat.Rda") 
save(lat_resp_dat, file="../import_files/lat_resp_dat.txt") 
save(lat_resp_dat, file="../excel_files/lat_resp_dat.csv") 
